version: '3.8'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./setup_mysql_dev.sql:/docker-entrypoint-initdb.d/setup_mysql_dev.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hbnb_dev_db
      - MYSQL_USER=hbnb_dev
      - MYSQL_PASSWORD=hbnb_dev_pwd